[project]
name = 'Blockchain-Based-Specialized-Collectible-Card-Authentication'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.card-registration]
path = 'contracts/card-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.grading-certification]
path = 'contracts/grading-certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.ownership-transfer]
path = 'contracts/ownership-transfer.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
